package Boundary;

import Control.ControllerAccessoUtente;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;

import java.util.Map;
import java.util.HashMap;

public class GUIAccessoUtente {

    private JPanel contentPanel;
    private JLabel logoLabel;
    private JTextField txtEmail;
    private JPasswordField txtPassword;
    private JButton annullaButton;
    private JButton accediButton;

    private ControllerAccessoUtente controllerAccessoUtente;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(10, 2, new Insets(10, 8, 10, 8), -1, -1));
        contentPanel.setPreferredSize(new Dimension(500, 350));
        logoLabel = new JLabel();
        logoLabel.setText("");
        contentPanel.add(logoLabel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        contentPanel.add(separator1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Inserisci le credenziali per autenticarti e accedere alle funzionalità del sistema");
        contentPanel.add(label1, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator2 = new JSeparator();
        contentPanel.add(separator2, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Email");
        contentPanel.add(label2, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtEmail = new JTextField();
        contentPanel.add(txtEmail, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Password");
        contentPanel.add(label3, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator3 = new JSeparator();
        contentPanel.add(separator3, new GridConstraints(6, 0, 1, 2, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        annullaButton = new JButton();
        annullaButton.setText("Annulla");
        contentPanel.add(annullaButton, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        accediButton = new JButton();
        accediButton.setText("Accedi");
        contentPanel.add(accediButton, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator4 = new JSeparator();
        contentPanel.add(separator4, new GridConstraints(8, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Esito");
        contentPanel.add(label4, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setForeground(new Color(-14535975));
        label5.setText("In attesa di inserimento...");
        contentPanel.add(label5, new GridConstraints(9, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPassword = new JPasswordField();
        contentPanel.add(txtPassword, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();

        GUIAccessoUtente guiAccessoUtente = new GUIAccessoUtente();

        frame.setTitle("Accesso Utente");
        frame.setContentPane(guiAccessoUtente.getContentPanel());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    /**
     * Costruisce la GUI di accesso utente.

     * La Boundary inizializza il controller tecnico di accesso, carica il logo
     * e collega i pulsanti alle rispettive azioni grafiche.

     * La GUI non crea Credenziali, non accede a Utente, non interroga il Database
     * e non gestisce direttamente la sessione applicativa.
     */

    public GUIAccessoUtente() {

        this.controllerAccessoUtente = new ControllerAccessoUtente();

        caricaLogo();

        annullaButton.addActionListener(new ActionListener() {

            /**
             * Gestisce l'annullamento dell'accesso e riporta alla Home Page.

             * @param e evento generato dalla pressione del pulsante Annulla
             */

            @Override
            public void actionPerformed(ActionEvent e) {
                tornaAllaHomePage();
            }
        });

        accediButton.addActionListener(new ActionListener() {

            /**
             * Gestisce la richiesta di accesso dell'utente.
             * Acquisisce i dati inseriti nella GUI e li inoltra al metodo
             * responsabile della delega verso il ControllerAccessoUtente.

             * @param e evento generato dalla pressione del pulsante Accedi
             */

            @Override
            public void actionPerformed(ActionEvent e) {

                Map<String, Object> datiAccesso = acquisisciDatiAccesso();
                inviaDatiAccesso(datiAccesso);
            }
        });
    }

    /**
     * Acquisisce i dati inseriti dall'utente nella GUI di accesso.

     * La Boundary raccoglie esclusivamente dati semplici, cioè email e password,
     * e li organizza in una Map<String, Object> da inoltrare al livello Control.
     * Il metodo non crea Credenziali, non accede a Utente e non effettua
     * verifiche sulla persistenza, rispettando la separazione BCED tra
     * Boundary, Control, Entity e Database.
     * @return mappa contenente email e password inserite dall'utente
     */

    public Map<String, Object> acquisisciDatiAccesso() {

        Map<String, Object> datiAccesso = new HashMap<>();

        datiAccesso.put("email", valoreTestuale(txtEmail.getText()));

        datiAccesso.put("password", new String(txtPassword.getPassword()));

        return datiAccesso;
    }

    /**
     * Invia i dati di accesso al ControllerAccessoUtente.
     *
     * La Boundary acquisisce le credenziali inserite dall'utente,
     * verifica formalmente la presenza dei campi obbligatori e delega
     * al ControllerAccessoUtente la verifica della precondizione di accesso.
     *
     * L'accesso non è gestito dal ControllerServiziSistema dei casi d'uso
     * principali, ma dal controller dedicato alla precondizione di autenticazione.
     *
     * @param datiAccesso dati semplici contenenti email e password
     */
    public void inviaDatiAccesso(Map<String, Object> datiAccesso) {

        if (!validaCampiAccesso(datiAccesso)) {
            segnalaErroreAccesso(
                    "Inserisci email e password per effettuare l'accesso."
            );
            return;
        }

        Map<String, Object> datiSessioneUtente =
                controllerAccessoUtente.verificaCredenzialiAccesso(datiAccesso);

        if (datiSessioneUtente == null || datiSessioneUtente.isEmpty()) {
            segnalaErroreAccesso(
                    "Credenziali non valide. Verifica email e password."
            );
            return;
        }

        comunicaAccessoRiuscito();
        apriDashboard(datiSessioneUtente);
    }

    private void tornaAllaHomePage() {
        GUIHomePage guiHomePage = new GUIHomePage();

        JFrame frameHome = new JFrame("Sistema Comunale Gestione Segnalazioni");
        frameHome.setContentPane(guiHomePage.getContentPanel());
        frameHome.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frameHome.setResizable(false);
        frameHome.pack();
        frameHome.setLocationRelativeTo(null);
        frameHome.setVisible(true);

        Window finestraCorrente = SwingUtilities.getWindowAncestor(contentPanel);

        if (finestraCorrente != null) {
            finestraCorrente.dispose();
        }
    }

    public JPanel getContentPanel() {
        return contentPanel;
    }

    private void caricaLogo() {
        URL urlLogo = getClass().getResource("/images/logo.png");

        if (urlLogo == null) {
            System.err.println("Logo non trovato.");
            return;
        }

        ImageIcon logo = new ImageIcon(urlLogo);

        Image immagine = logo.getImage();
        Image immagineRidimensionata = immagine.getScaledInstance(
                100,
                100,
                Image.SCALE_SMOOTH
        );

        logoLabel.setIcon(new ImageIcon(immagineRidimensionata));
        logoLabel.setText("");
        logoLabel.setHorizontalAlignment(SwingConstants.CENTER);
    }

    public void comunicaAccessoRiuscito() {
        JOptionPane.showMessageDialog(
                contentPanel,
                "Accesso effettuato con successo.",
                "Accesso riuscito",
                JOptionPane.INFORMATION_MESSAGE
        );
    }

    /**
     * Comunica all'utente un errore relativo alla procedura di accesso.
     *
     * La Boundary gestisce esclusivamente la comunicazione grafica dell'esito
     * negativo, mentre il livello Control restituisce solo un esito semplice
     * relativo alla validità delle credenziali.
     *
     * @param messaggio descrizione dell'errore da mostrare all'utente
     */
    public void segnalaErroreAccesso(String messaggio) {

        String messaggioDaMostrare = valoreTestuale(messaggio);

        if (isVuoto(messaggioDaMostrare)) {
            messaggioDaMostrare = "Accesso non completato. Verifica le credenziali inserite.";
        }

        JOptionPane.showMessageDialog(
                contentPanel,
                messaggioDaMostrare,
                "Errore accesso",
                JOptionPane.ERROR_MESSAGE
        );
    }

    /**
     * Apre la dashboard dell'utente autenticato e chiude la finestra di accesso.
     *
     * Questo metodo è un supporto tecnico della Boundary per la navigazione
     * tra schermate. Non rappresenta una responsabilità di dominio e non viene
     * inserito nel modello Entity.
     *
     * Il metodo riceve solo dati semplici di sessione prodotti dal livello
     * Control/Facade Entity, senza ricevere né propagare istanze Entity di Utente.
     *
     * @param datiSessioneUtente mappa contenente idUtente, nome, cognome e ruolo
     */
    private void apriDashboard(Map<String, Object> datiSessioneUtente) {

        if (!validaDatiSessioneUtente(datiSessioneUtente)) {
            segnalaErroreAccesso(
                    "Sessione utente non valida. Effettua nuovamente l'accesso."
            );
            return;
        }

        GUIDashboardUtente guiDashboard = new GUIDashboardUtente(datiSessioneUtente);

        JFrame frameDashboard = new JFrame("Dashboard Utente");
        frameDashboard.setContentPane(guiDashboard.getContentPanel());
        frameDashboard.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frameDashboard.setResizable(false);
        frameDashboard.pack();
        frameDashboard.setLocationRelativeTo(null);
        frameDashboard.setVisible(true);

        Window finestraCorrente = SwingUtilities.getWindowAncestor(contentPanel);

        if (finestraCorrente != null) {
            finestraCorrente.dispose();
        }
    }

    /**
     * Verifica che i campi necessari per l'accesso siano stati compilati.
     * La validazione è solo formale e riguarda i dati acquisiti dalla Boundary:
     * controlla che email e password non siano vuote.
     * La verifica effettiva delle credenziali non viene effettuata nella GUI,
     * ma resta responsabilità del livello Control e del Facade Entity.
     * @param datiAccesso mappa contenente i dati acquisiti dalla GUI
     * @return true se email e password sono valorizzate, false altrimenti
     */

    private boolean validaCampiAccesso(Map<String, Object> datiAccesso) {

        if (datiAccesso == null) {
            return false;
        }
        String email = valoreTestuale(datiAccesso.get("email"));

        String password = valoreTestuale(datiAccesso.get("password"));

        return !isVuoto(email) && !isVuoto(password);
    }

    /**
     * Converte un valore generico in una stringa pulita.
     * Metodo privato di supporto usato dalla Boundary per normalizzare
     * i dati acquisiti dai componenti Swing prima di inoltrarli al livello Control.
     * @param valore valore da convertire
     * @return stringa senza spazi iniziali/finali, oppure stringa vuota se il valore è nullo
     */

    private String valoreTestuale(Object valore) {

        if (valore == null) {

            return "";
        }
        return valore.toString().trim();
    }

    /**
     * Verifica se una stringa è nulla o vuota.
     * Metodo privato di supporto alla validazione formale dei campi della GUI.
     * Non espone logica di dominio e non accede alle Entity.
     * @param valore stringa da verificare
     * @return true se il valore è nullo o vuoto, false altrimenti
     */

    private boolean isVuoto(String valore) {

        return valore == null || valore.trim().isEmpty();
    }

    /**
     * Verifica che i dati semplici di sessione siano utilizzabili dalla dashboard.

     * La Boundary non verifica credenziali e non accede al dominio: controlla
     * soltanto che la Map ricevuta dal controller contenga almeno l'identificativo
     * dell'utente autenticato e il ruolo necessario alla configurazione della
     * dashboard.

     * @param datiSessioneUtente mappa contenente i dati semplici dell'utente autenticato
     * @return true se i dati minimi di sessione sono presenti, false altrimenti

     */

    private boolean validaDatiSessioneUtente(Map<String, Object> datiSessioneUtente) {

        if (datiSessioneUtente == null) {

            return false;

        }

        Object idUtente = datiSessioneUtente.get("idUtente");

        String ruolo = valoreTestuale(datiSessioneUtente.get("ruolo"));

        return idUtente != null && !isVuoto(ruolo);
    }
}
