package Boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;

public class GUIHomePage {

    private JPanel contentPanel;
    private JButton registratiButton;
    private JButton accediButton;
    private JLabel logoLabel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(8, 3, new Insets(10, 10, 10, 10), -1, -1));
        contentPanel.setPreferredSize(new Dimension(550, 350));
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-14535975));
        label1.setHorizontalAlignment(0);
        label1.setText("Sistema Comunale Gestione Segnalazioni");
        contentPanel.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Benvenuto/a nella piattaforma per la gestione delle segnalazioni relative al territorio");
        contentPanel.add(label2, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        contentPanel.add(separator1, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JSeparator separator2 = new JSeparator();
        contentPanel.add(separator2, new GridConstraints(3, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        registratiButton = new JButton();
        registratiButton.setText("Registrati");
        contentPanel.add(registratiButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        accediButton = new JButton();
        accediButton.setText("Accedi");
        contentPanel.add(accediButton, new GridConstraints(4, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator3 = new JSeparator();
        contentPanel.add(separator3, new GridConstraints(5, 0, 2, 3, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setForeground(new Color(-16777216));
        label3.setHorizontalAlignment(0);
        label3.setText("Progetto di Ingegneria del Software - GR10");
        contentPanel.add(label3, new GridConstraints(7, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logoLabel = new JLabel();
        logoLabel.setText("");
        contentPanel.add(logoLabel, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }


    public static void main(String[] args) {
        JFrame frame = new JFrame();

        GUIHomePage home = new GUIHomePage();

        frame.setTitle("HomePage");
        frame.setContentPane(home.getContentPanel());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    /**
     * Costruisce la Home Page del sistema.

     * La Home Page rappresenta una Boundary iniziale e ha il solo compito di:
     * - mostrare le opzioni principali all'utente;
     * - consentire la navigazione verso la registrazione;
     * - consentire la navigazione verso l'accesso.

     * La classe non accede al livello Control, non accede alle Entity e non
     * gestisce logica di dominio. Le schermate successive si occuperanno di
     * delegare le richieste ai rispettivi controller.
     */

    public GUIHomePage() {

        caricaLogo();

        registratiButton.addActionListener(new ActionListener() {

            /**
             * Gestisce la richiesta di apertura della GUI di registrazione.
             * La Home Page non esegue alcuna registrazione: si limita ad aprire
             * la Boundary dedicata.

             * @param e evento generato dalla pressione del pulsante Registrati
             */

            @Override
            public void actionPerformed(ActionEvent e) {

                richiediRegistrazione();
            }
        });

        accediButton.addActionListener(new ActionListener() {

            /**
             * Gestisce la richiesta di apertura della GUI di accesso.
             * La Home Page non verifica credenziali e non autentica utenti:
             * si limita ad aprire la Boundary dedicata all'accesso.

             * @param e evento generato dalla pressione del pulsante Accedi
             */

            @Override
            public void actionPerformed(ActionEvent e) {

                richiediAccesso();
            }
        });
    }

    /**
     * Apre la GUI di registrazione utente.

     * Il metodo appartiene alla Boundary e svolge solo una responsabilità
     * tecnica di navigazione tra schermate.

     * Non crea Utente, non crea Credenziali, non accede alla persistenza e non
     * invoca direttamente il livello Control. La registrazione effettiva verrà
     * gestita dalla GUIRegistrazioneUtente tramite la catena Boundary → Control.
     */

    public void richiediRegistrazione() {

        GUIRegistrazioneUtente guiRegistrazione = new GUIRegistrazioneUtente();

        JFrame frameRegistrazione = new JFrame("Registrazione Utente");

        frameRegistrazione.setContentPane(guiRegistrazione.getContentPanel());

        frameRegistrazione.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        frameRegistrazione.setResizable(false);

        frameRegistrazione.pack();

        frameRegistrazione.setLocationRelativeTo(null);

        frameRegistrazione.setVisible(true);

        chiudiFinestraCorrente();
    }

    /**
     * Apre la GUI di accesso utente.

     * Il metodo appartiene alla Boundary e svolge solo una responsabilità
     * tecnica di navigazione tra schermate.

     * Non verifica credenziali, non accede a Credenziali, non accede alla
     * persistenza e non autentica direttamente l'utente. L'accesso effettivo
     * verrà gestito dalla GUIAccessoUtente tramite il ControllerAccessoUtente.
     */

    public void richiediAccesso() {

        GUIAccessoUtente guiAccesso = new GUIAccessoUtente();

        JFrame frameAccesso = new JFrame("Accesso Utente");

        frameAccesso.setContentPane(guiAccesso.getContentPanel());

        frameAccesso.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        frameAccesso.setResizable(false);

        frameAccesso.pack();

        frameAccesso.setLocationRelativeTo(null);

        frameAccesso.setVisible(true);

        chiudiFinestraCorrente();
    }

    public JPanel getContentPanel() {
        return contentPanel;
    }

    /**
     * Carica il logo della Home Page dalle risorse dell'applicazione.

     * Il metodo svolge una responsabilità esclusivamente grafica della Boundary.
     * Non accede al dominio, non accede alla persistenza e non interagisce
     * con il livello Control.

     * Se il logo non viene trovato, il metodo non interrompe l'applicazione:
     * mostra solo un messaggio su standard error.
     */

    private void caricaLogo() {

        URL urlLogo = getClass().getResource("/images/logo.png");

        if (urlLogo == null) {

            System.err.println("[GUIHomePage] Logo non trovato.");
            return;
        }
        ImageIcon logo = new ImageIcon(urlLogo);

        Image immagine = logo.getImage();

        Image immagineRidimensionata = immagine.getScaledInstance(

                100,
                100,
                Image.SCALE_SMOOTH

        );
        logoLabel.setIcon(new ImageIcon(immagineRidimensionata));

        logoLabel.setText("");

        logoLabel.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * Chiude la finestra Swing attualmente associata alla Home Page.

     * Il metodo è un supporto tecnico di navigazione della Boundary e serve
     * a evitare duplicazioni di finestre dopo l'apertura di una nuova schermata.

     * Non rappresenta una responsabilità di dominio e non deve essere modellato
     * nelle Entity.
     */

    private void chiudiFinestraCorrente() {

        Window finestraCorrente = SwingUtilities.getWindowAncestor(contentPanel);

        if (finestraCorrente != null) {

            finestraCorrente.dispose();
        }
    }
}
