package Boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFormattedTextField;

import java.util.Map;
import java.util.HashMap;

import Control.ControllerServiziSistema;


public class GUIRegistrazioneUtente {
    private JTextField txtNome;
    private JLabel Inf_nome;
    private JTextField txtCognome;
    private JLabel Inf_cognome;
    private JTextField txtEmail;
    private JLabel Inf_email;
    private JFormattedTextField numtelfField;
    private JLabel Inf_numTel;
    private JPasswordField txtRecapitoTelefonico;
    private JLabel Inf_psw;
    private JPasswordField txtPassword;
    private JLabel Inf_Conf_psw;
    private JComboBox boxRuolo;
    private JButton registratiButton;
    private JLabel Inf_Ruolo;
    private JPanel contentPanel;

    private ControllerServiziSistema controllerServiziSistema;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public GUIRegistrazioneUtente() {

        this.controllerServiziSistema = new ControllerServiziSistema();

        registratiButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                inviaDatiRegistrazione(acquisisciDatiRegistrazione());
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(15, 3, new Insets(10, 10, 10, 10), -1, -1));
        contentPanel.setPreferredSize(new Dimension(450, 400));
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setText("Inserisci i dati richiesti per completare la registrazione.");
        label1.setVerticalAlignment(0);
        contentPanel.add(label1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPanel.add(spacer1, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        contentPanel.add(separator1, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        Inf_nome = new JLabel();
        Inf_nome.setText("Nome");
        contentPanel.add(Inf_nome, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNome = new JTextField();
        contentPanel.add(txtNome, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        Inf_cognome = new JLabel();
        Inf_cognome.setText("Cognome");
        contentPanel.add(Inf_cognome, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtCognome = new JTextField();
        contentPanel.add(txtCognome, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        Inf_email = new JLabel();
        Inf_email.setText("Email");
        contentPanel.add(Inf_email, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtEmail = new JTextField();
        contentPanel.add(txtEmail, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        Inf_numTel = new JLabel();
        Inf_numTel.setText("Recapito telefonico");
        contentPanel.add(Inf_numTel, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        numtelfField = new JFormattedTextField();
        contentPanel.add(numtelfField, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        Inf_psw = new JLabel();
        Inf_psw.setText("Password");
        contentPanel.add(Inf_psw, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtRecapitoTelefonico = new JPasswordField();
        contentPanel.add(txtRecapitoTelefonico, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        Inf_Conf_psw = new JLabel();
        Inf_Conf_psw.setText("Conferma Password");
        contentPanel.add(Inf_Conf_psw, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPassword = new JPasswordField();
        contentPanel.add(txtPassword, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JSeparator separator2 = new JSeparator();
        contentPanel.add(separator2, new GridConstraints(8, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        boxRuolo = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Cittadino");
        defaultComboBoxModel1.addElement("Operatore Comunale");
        boxRuolo.setModel(defaultComboBoxModel1);
        contentPanel.add(boxRuolo, new GridConstraints(9, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        contentPanel.add(spacer2, new GridConstraints(11, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        registratiButton = new JButton();
        registratiButton.setText("Registrati");
        contentPanel.add(registratiButton, new GridConstraints(12, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Esito");
        contentPanel.add(label2, new GridConstraints(14, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setForeground(new Color(-14535975));
        label3.setHorizontalAlignment(0);
        label3.setText("In attesa di inserimento...");
        contentPanel.add(label3, new GridConstraints(14, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Inf_Ruolo = new JLabel();
        Inf_Ruolo.setText("Ruolo");
        contentPanel.add(Inf_Ruolo, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator3 = new JSeparator();
        contentPanel.add(separator3, new GridConstraints(13, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JSeparator separator4 = new JSeparator();
        contentPanel.add(separator4, new GridConstraints(10, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();

        GUIRegistrazioneUtente guiRegistrazione = new GUIRegistrazioneUtente();

        frame.setTitle("Registrazione Utente");
        frame.setContentPane(guiRegistrazione.getContentPanel());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    public JPanel getContentPanel() {
        return contentPanel;
    }

    public Map<String, Object> acquisisciDatiRegistrazione() {

        Map<String, Object> datiRegistrazione = new HashMap<>();

        String nome = valoreTestuale(txtNome.getText());

        String cognome = valoreTestuale(txtCognome.getText());

        String email = valoreTestuale(txtEmail.getText());

        // --- SOLUZIONE DEL BUG DI INTELLIJ ---
        // numtelfField è posizionato sulla riga "Recapito telefonico"
        String recapitoTelefonico = valoreTestuale(numtelfField.getText());

        // txtRecapitoTelefonico è posizionato sulla riga della "Password"
        String password = new String(txtRecapitoTelefonico.getPassword());

        // txtPassword è posizionato sulla riga di "Conferma Password"
        String confermaPassword = new String(txtPassword.getPassword());

        String ruolo = valoreTestuale(boxRuolo.getSelectedItem());

        datiRegistrazione.put("nome", nome);

        datiRegistrazione.put("cognome", cognome);

        datiRegistrazione.put("email", email);

        datiRegistrazione.put("recapitoTelefonico", recapitoTelefonico);

        datiRegistrazione.put("password", password);

        datiRegistrazione.put("confermaPassword", confermaPassword);

        datiRegistrazione.put("ruolo", ruolo);

        return datiRegistrazione;

    }

    public void inviaDatiRegistrazione(Map<String, Object> datiRegistrazione) {
        try {
            // 1. Validazione formale della GUI (lancia eccezione se fallisce)
            validaCampiRegistrazione(datiRegistrazione);

            // 2. Delega al livello Control
            boolean registrazioneRiuscita = controllerServiziSistema.registraUtente(datiRegistrazione);

            if (registrazioneRiuscita) {
                comunicaConfermaRegistrazione();
                tornaAllaHomePage();
            } else {
                segnalaErroreRegistrazione("Registrazione non completata. Verifica i dati inseriti.");
            }

        } catch (IllegalArgumentException e) {
            // Cattura il messaggio specifico del Piano di Test e lo mostra nella JOptionPane
            segnalaErroreRegistrazione(e.getMessage());
        }
    }

    /**
     * Comunica all'utente un errore relativo alla registrazione.
     *
     * @param messaggio descrizione dell'errore da mostrare nella GUI
     */
    public void segnalaErroreRegistrazione(String messaggio) {

        String messaggioDaMostrare = valoreTestuale(messaggio);

        if (isVuoto(messaggioDaMostrare)) {
            messaggioDaMostrare = "Registrazione non completata.";
        }

        JOptionPane.showMessageDialog(
                contentPanel,
                messaggioDaMostrare,
                "Errore registrazione",
                JOptionPane.ERROR_MESSAGE
        );
    }

    /**
     * Comunica all'utente la conclusione positiva della registrazione.
     */
    public void comunicaConfermaRegistrazione() {

        JOptionPane.showMessageDialog(
                contentPanel,
                "Registrazione completata con successo.",
                "Conferma registrazione",
                JOptionPane.INFORMATION_MESSAGE
        );
    }

    /**
     * Verifica la correttezza formale dei dati inseriti nella GUI di registrazione.
     */
    private boolean validaCampiRegistrazione(Map<String, Object> datiRegistrazione) {
        if (datiRegistrazione == null) {
            throw new IllegalArgumentException("Dati di registrazione mancanti.");
        }

        String nome = valoreTestuale(datiRegistrazione.get("nome"));
        String cognome = valoreTestuale(datiRegistrazione.get("cognome"));
        String email = valoreTestuale(datiRegistrazione.get("email"));
        String recapitoTelefonico = valoreTestuale(datiRegistrazione.get("recapitoTelefonico"));
        String password = valoreTestuale(datiRegistrazione.get("password"));
        String confermaPassword = valoreTestuale(datiRegistrazione.get("confermaPassword"));
        String ruolo = valoreTestuale(datiRegistrazione.get("ruolo"));

        // Controlli presenza campi obbligatori
        if (isVuoto(nome)) throw new IllegalArgumentException("Il campo Nome è obbligatorio"); //
        if (isVuoto(cognome)) throw new IllegalArgumentException("Il campo Cognome è obbligatorio"); //
        if (isVuoto(email)) throw new IllegalArgumentException("Il campo Email è obbligatorio"); //
        if (isVuoto(recapitoTelefonico)) throw new IllegalArgumentException("Il campo Recapito Telefonico è obbligatorio");
        if (isVuoto(password)) throw new IllegalArgumentException("Il campo Password è obbligatorio");
        if (isVuoto(ruolo)) throw new IllegalArgumentException("Selezionare il proprio ruolo dal menù"); // [cite: 52]

        if (!password.equals(confermaPassword)) {
            throw new IllegalArgumentException("Le password inserite non coincidono.");
        }

        // Controlli sui formati (Duplicati nella GUI per intercettazione immediata)
        if (nome.length() > 50 || nome.matches(".*[0-9!@#$%^&*(),.?\":{}|<>].*")) {
            throw new IllegalArgumentException("Formato Nome non valido o troppo lungo"); //
        }
        if (!Character.isUpperCase(nome.charAt(0))) {
            throw new IllegalArgumentException("Il Nome deve iniziare con una lettera maiuscola"); //
        }
        if (cognome.length() > 50 || cognome.matches(".*[0-9!@#$%^&*(),.?\":{}|<>].*")) {
            throw new IllegalArgumentException("Formato Cognome non valido o troppo lungo"); //
        }
        if (!Character.isUpperCase(cognome.charAt(0))) {
            throw new IllegalArgumentException("Il Cognome deve iniziare con una lettera maiuscola"); //
        }
        if (!email.contains("@") || email.contains(" ") || !email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
            throw new IllegalArgumentException("Formato Email non valido"); //
        }
        if (!recapitoTelefonico.matches("^\\d+$")) {
            throw new IllegalArgumentException("Il recapito deve contenere solo numeri"); // [cite: 52]
        }
        if (recapitoTelefonico.length() != 10) {
            throw new IllegalArgumentException("La lunghezza del recapito non è valida"); // [cite: 52]
        }

        return true;
    }

    private void tornaAllaHomePage() {
        GUIHomePage guiHomePage = new GUIHomePage();

        JFrame frameHome = new JFrame("Sistema Comunale Gestione Segnalazioni");
        frameHome.setContentPane(guiHomePage.getContentPanel());
        frameHome.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frameHome.setResizable(false);
        frameHome.pack();
        frameHome.setLocationRelativeTo(null);
        frameHome.setVisible(true);

        Window finestraCorrente = SwingUtilities.getWindowAncestor(contentPanel);

        if (finestraCorrente != null) {
            finestraCorrente.dispose();
        }
    }

    private String valoreTestuale(Object valore) {
        if (valore == null) {
            return "";
        }
        return valore.toString().trim();
    }

    private boolean isVuoto(String valore) {
        return valore == null || valore.trim().isEmpty();
    }
}